### ISSUE TITLE
OpenSSL version?

### ISSUE THREAD

**Issue by danxinnoble** [KULeuven-COSIC/SCALE-MAMBA#14]
Which version of OpenSSL 1.1.0 did you test with? There seem to be various iterations of 1.1.0 (see https://github.com/openssl/openssl/releases). Previously, I was using 1.1.0_h, which seems to have worked fine up to SCALE-MAMBA v1.2. However, when I tried to run "make progs" with SCALE-MAMBA v1.3 with OpenSSL 1.1.0_h, I got the following error:
****
OT/CRS.h:17:31: fatal error: cryptopp/eccrypto.h: No such file or directory
compilation terminated. 
Makefile:33: recipe for target 'OT/LaAND.o' failed 
****

**Comment by rdragos** [comment]
Hi Daniel,

You're missing the cryptopp library. Check out the tutorial for installing SCALE: https://rdragos.github.io/2019/01/07/scale/

PS: The reason why cryptopp installations steps are missing is that I copy pasted my blog contents (which corresponded to previous version of S&M 1.2). I've updated my blog since that's faster than pushing for a new version of documentation on Github.
