### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by thanosgn** [KULeuven-COSIC/SCALE-MAMBA#2]
Hello,

I am experimenting with SCALE-MAMBA and as I was running the _IO_demo_ example I noticed that when the program is expecting input, the CPU is at 100% and the memory keeps rising until my pc runs out.

I am attaching a screenshot of a sample execution.
![iodemo](https://user-images.githubusercontent.com/8928288/44780061-c217a980-ab89-11e8-99e9-a289c0051371.png)

Do you think there is an issue causing memory leak?

Thanks

**Comment by NigelSmart** [comment]
Because it keeps producing offline data one presumes.

Make sure if you run on a single local machine for full threshold
you use the flag
	-f 1
to ensure only one FHE factory is used (otherwise memory really
will be used up).

Even then you will need about 32 GB of RAM to run two-party full
threshold on one local machine.

Nigel

**Comment by thanosgn** [comment]
Thanks for the immediate reply!

OK I'll keep that in mind.

Since it's not a memory leak I'm closing the issue.

Thanks again
