### ISSUE TITLE
Getting 'receiving error' at the end, even though everything runs fine.

### ISSUE THREAD

**Issue by danxinnoble** [KULeuven-COSIC/SCALE-MAMBA#20]
Hi

I'm getting an error when running normal programs:
terminate called after throwing an instance of 'receiving_error'

This is in version 1.4.1 (commit 25a657a). I did the following:
$ make progs
$ ./genSetupOptions.sh 4 1 | ./Setup.x  # 4 local parties, non-fake everything, Shamir with t=1
$ ./compile.py Programs/tutorial
$ ./Player.x 0 Programs/tutorial/ &
$ ./Player.x 1 Programs/tutorial/ &
$ ./Player.x 2 Programs/tutorial/ &
$ ./Player.x 3 Programs/tutorial/ &

The odd thing is that it runs fine all the way to the end (outputs "explected 789, got 789"). It's just after everything is done that this error gets thrown.

Any thoughts on what is going on?

Best
Daniel

**Comment by NigelSmart** [comment]
Try downloading an update I just pushed and recompiling everything.

Also post issues to the mailing list. I only saw this as I was doing a push to our public repo

**Comment by kobeee** [comment]
> Try downloading an update I just pushed and recompiling everything.
> 
> Also post issues to the mailing list. I only saw this as I was doing a push to our public repo

Hi, NigelSmart. I was using the latest version of scalemamba and I still got the "receving error" whatever I ran in the Programs folder. I ran with 3 players and I choosed Shamir Sharing, all I got under gdb were the same as followed:

(gdb) run 0 ./Programs/tutorial/
Starting program: /root/SCALE-MAMBA/Player.x 0 ./Programs/tutorial/
warning: Error disabling address space randomization: Operation not permitted
(Min,Max) number of ...
	(0,infty) multiplication triples
	(0,infty) square pairs
	(0,infty) bits
0
127.0.0.1
Player0.crt
player0@example.com
1
172.17.0.3
Player1.crt
player1@example.com
2
172.17.0.4
Player2.crt
player2@example.com


p=2147483999
sm::0:: loading certificate from Cert-Store/Player0.crt
Opening file ./Programs/tutorial//tutorial.sch
Number of online threads I will run in parallel =  1
Number of program sequences I need to load =  1
Loading program 0 from ./Programs/tutorial//tutorial-0.bc
All connections now done
Setting up threads
Waiting for thread 0 to be ready
I am player 0 in thread 20000
I am player 0 in thread 20001
I am player 0 in thread 4
I am player 0 in thread 3
I am player 0 in thread 2
I am player 0 in thread 1
I am player 0 in thread 0
Set up player 0 in thread 1 
Set up player 0 in thread 4 
Doing online for player 0 in online thread 0
Set up player 0 in thread 3 
Set up player 0 in thread 20001 
Set up player 0 in thread 20000 
Set up player 0 in thread 2 
Set up player 0 in thread 0 
terminate called after throwing an instance of 'receiving_error'
  what():  Receiving error
During startup program terminated with signal SIGABRT, Aborted.
(gdb) 
(gdb) bt
No stack.

I guess that "signal SIGABRT" may be caused by double free or abort function, by I was confusing how to fix it. The programs were runing in three docker containers as 3 player and all dockers were run in just one machine. Is that may be the reason cause this error for something like out of memory or ...?
I hope that you can help me, thank you very much!!!

**Comment by liliarizona** [comment]
> > Try downloading an update I just pushed and recompiling everything.
> > Also post issues to the mailing list. I only saw this as I was doing a push to our public repo
> 
> Hi, NigelSmart. I was using the latest version of scalemamba and I still got the "receving error" whatever I ran in the Programs folder. I ran with 3 players and I choosed Shamir Sharing, all I got under gdb were the same as followed:
> 
> (gdb) run 0 ./Programs/tutorial/
> Starting program: /root/SCALE-MAMBA/Player.x 0 ./Programs/tutorial/
> warning: Error disabling address space randomization: Operation not permitted
> (Min,Max) number of ...
> (0,infty) multiplication triples
> (0,infty) square pairs
> (0,infty) bits
> 0
> 127.0.0.1
> Player0.crt
> [player0@example.com](mailto:player0@example.com)
> 1
> 172.17.0.3
> Player1.crt
> [player1@example.com](mailto:player1@example.com)
> 2
> 172.17.0.4
> Player2.crt
> [player2@example.com](mailto:player2@example.com)
> 
> p=2147483999
> sm::0:: loading certificate from Cert-Store/Player0.crt
> Opening file ./Programs/tutorial//tutorial.sch
> Number of online threads I will run in parallel = 1
> Number of program sequences I need to load = 1
> Loading program 0 from ./Programs/tutorial//tutorial-0.bc
> All connections now done
> Setting up threads
> Waiting for thread 0 to be ready
> I am player 0 in thread 20000
> I am player 0 in thread 20001
> I am player 0 in thread 4
> I am player 0 in thread 3
> I am player 0 in thread 2
> I am player 0 in thread 1
> I am player 0 in thread 0
> Set up player 0 in thread 1
> Set up player 0 in thread 4
> Doing online for player 0 in online thread 0
> Set up player 0 in thread 3
> Set up player 0 in thread 20001
> Set up player 0 in thread 20000
> Set up player 0 in thread 2
> Set up player 0 in thread 0
> terminate called after throwing an instance of 'receiving_error'
> what(): Receiving error
> During startup program terminated with signal SIGABRT, Aborted.
> (gdb)
> (gdb) bt
> No stack.
> 
> I guess that "signal SIGABRT" may be caused by double free or abort function, by I was confusing how to fix it. The programs were runing in three docker containers as 3 player and all dockers were run in just one machine. Is that may be the reason cause this error for something like out of memory or ...?
> I hope that you can help me, thank you very much!!!

+1 seeing the same error.... frustrated....

**Comment by liliarizona** [comment]
> > Try downloading an update I just pushed and recompiling everything.
> > Also post issues to the mailing list. I only saw this as I was doing a push to our public repo
> 
> Hi, NigelSmart. I was using the latest version of scalemamba and I still got the "receving error" whatever I ran in the Programs folder. I ran with 3 players and I choosed Shamir Sharing, all I got under gdb were the same as followed:
> 
> (gdb) run 0 ./Programs/tutorial/
> Starting program: /root/SCALE-MAMBA/Player.x 0 ./Programs/tutorial/
> warning: Error disabling address space randomization: Operation not permitted
> (Min,Max) number of ...
> (0,infty) multiplication triples
> (0,infty) square pairs
> (0,infty) bits
> 0
> 127.0.0.1
> Player0.crt
> [player0@example.com](mailto:player0@example.com)
> 1
> 172.17.0.3
> Player1.crt
> [player1@example.com](mailto:player1@example.com)
> 2
> 172.17.0.4
> Player2.crt
> [player2@example.com](mailto:player2@example.com)
> 
> p=2147483999
> sm::0:: loading certificate from Cert-Store/Player0.crt
> Opening file ./Programs/tutorial//tutorial.sch
> Number of online threads I will run in parallel = 1
> Number of program sequences I need to load = 1
> Loading program 0 from ./Programs/tutorial//tutorial-0.bc
> All connections now done
> Setting up threads
> Waiting for thread 0 to be ready
> I am player 0 in thread 20000
> I am player 0 in thread 20001
> I am player 0 in thread 4
> I am player 0 in thread 3
> I am player 0 in thread 2
> I am player 0 in thread 1
> I am player 0 in thread 0
> Set up player 0 in thread 1
> Set up player 0 in thread 4
> Doing online for player 0 in online thread 0
> Set up player 0 in thread 3
> Set up player 0 in thread 20001
> Set up player 0 in thread 20000
> Set up player 0 in thread 2
> Set up player 0 in thread 0
> terminate called after throwing an instance of 'receiving_error'
> what(): Receiving error
> During startup program terminated with signal SIGABRT, Aborted.
> (gdb)
> (gdb) bt
> No stack.
> 
> I guess that "signal SIGABRT" may be caused by double free or abort function, by I was confusing how to fix it. The programs were runing in three docker containers as 3 player and all dockers were run in just one machine. Is that may be the reason cause this error for something like out of memory or ...?
> I hope that you can help me, thank you very much!!!

OMG, I fixed it on my end.
So I found this post: https://groups.google.com/forum/#!topic/spdz/7P_TvBuPiysGB
According to the post, it is because docker is out of memory.
I had docker with 2GB memory when seeing the error.
After I increase the memory to 18.5GB, it's gone.
Try increase the memory assigned to docker.
In that post, Nigel Smart is suggesting assigning 8GB per player. But mine worked with 18.5GB for 3 players, so give it a try.

**Comment by kobeee** [comment]
> > > Try downloading an update I just pushed and recompiling everything.
> > > Also post issues to the mailing list. I only saw this as I was doing a push to our public repo
> > 
> > 
> > Hi, NigelSmart. I was using the latest version of scalemamba and I still got the "receving error" whatever I ran in the Programs folder. I ran with 3 players and I choosed Shamir Sharing, all I got under gdb were the same as followed:
> > (gdb) run 0 ./Programs/tutorial/
> > Starting program: /root/SCALE-MAMBA/Player.x 0 ./Programs/tutorial/
> > warning: Error disabling address space randomization: Operation not permitted
> > (Min,Max) number of ...
> > (0,infty) multiplication triples
> > (0,infty) square pairs
> > (0,infty) bits
> > 0
> > 127.0.0.1
> > Player0.crt
> > [player0@example.com](mailto:player0@example.com)
> > 1
> > 172.17.0.3
> > Player1.crt
> > [player1@example.com](mailto:player1@example.com)
> > 2
> > 172.17.0.4
> > Player2.crt
> > [player2@example.com](mailto:player2@example.com)
> > p=2147483999
> > sm::0:: loading certificate from Cert-Store/Player0.crt
> > Opening file ./Programs/tutorial//tutorial.sch
> > Number of online threads I will run in parallel = 1
> > Number of program sequences I need to load = 1
> > Loading program 0 from ./Programs/tutorial//tutorial-0.bc
> > All connections now done
> > Setting up threads
> > Waiting for thread 0 to be ready
> > I am player 0 in thread 20000
> > I am player 0 in thread 20001
> > I am player 0 in thread 4
> > I am player 0 in thread 3
> > I am player 0 in thread 2
> > I am player 0 in thread 1
> > I am player 0 in thread 0
> > Set up player 0 in thread 1
> > Set up player 0 in thread 4
> > Doing online for player 0 in online thread 0
> > Set up player 0 in thread 3
> > Set up player 0 in thread 20001
> > Set up player 0 in thread 20000
> > Set up player 0 in thread 2
> > Set up player 0 in thread 0
> > terminate called after throwing an instance of 'receiving_error'
> > what(): Receiving error
> > During startup program terminated with signal SIGABRT, Aborted.
> > (gdb)
> > (gdb) bt
> > No stack.
> > I guess that "signal SIGABRT" may be caused by double free or abort function, by I was confusing how to fix it. The programs were runing in three docker containers as 3 player and all dockers were run in just one machine. Is that may be the reason cause this error for something like out of memory or ...?
> > I hope that you can help me, thank you very much!!!
> 
> OMG, I fixed it on my end.
> So I found this post: https://groups.google.com/forum/#!topic/spdz/7P_TvBuPiysGB
> According to the post, it is because docker is out of memory.
> I had docker with 2GB memory when seeing the error.
> After I increase the memory to 18.5GB, it's gone.
> Try increase the memory assigned to docker.
> In that post, Nigel Smart is suggesting assigning 8GB per player. But mine worked with 18.5GB for 3 players, so give it a try.

Awesome! I will try it, thany you very much!
