### ISSUE TITLE
Differences between master and matrix branches?

### ISSUE THREAD

**Issue by sbellem** [KULeuven-COSIC/SCALE-MAMBA#26]
Hi,

 I am currently trying to run all the tests as per the script `run_tests.sh` and I get errors for the `master` 
branch that I do not get for the `matrix` branch. For instance for `Auto-Test-Data/25` and `test_array`, on the `master` branch I get

```shell
terminate called after throwing an instance of 'receiving_error'
  what():  Receiving error
  what():  Receiving error
  what():  Receiving error
  what():  Receiving error
  what():  Receiving error
terminate called recursively
```

Could someone confirm that they can successfully run all the tests for both branches?

Thank you very much!
Sylvain

---

Complete outputs for `Auto-Test-Data/25` `test_array` can be viewed at
* `master`: https://travis-ci.com/sbellem/SCALE-MAMBA/jobs/265899753#L390
* `matrix`: https://travis-ci.com/sbellem/SCALE-MAMBA/jobs/265899233#L390

**Comment by NigelSmart** [comment]
We have not tested the matrix branch in a while. This branch produced was for a specific purpose. The auto test data suite 25 uses a LOT of RAM, we also sometimes get problems. We are upgrading our testing suite to cope with this. The reason is that test suite 25 tries to simulate 10 players running on one machine, this obviously is pushing the RAM a bit as we optimize for one player running on one machine
