### ISSUE TITLE
Data importation from external clients (data providers)

### ISSUE THREAD

**Issue by cnasikas** [KULeuven-COSIC/SCALE-MAMBA#9]
Hi,

I would like to know if it is possible to implement the following architecture:

1. A cluster of 3 Players (computation nodes) using a Full Threshold secret sharing scheme.
2. External multiple data providers import data (shares) to the cluster.
3. The Players does not have access to the raw data.
4. The Players do the SMPC over the data when needed.

I have read the Documentation, and especially the IO class, I have see the code and the examples carefully, and read relative issues (#7).

I also have the following questions:

1. What is the different between private input / output and share input / output ?
2. The documentation says that the IO functions can be called from the MAMBA functions. Can we use the IO class without MAMBA ?

Thanks a lot!

**Comment by NigelSmart** [comment]
Item 2 is missing.

As for Item 1 just run Setup.x and choose three player full
threshold!

**Comment by cnasikas** [comment]
Hi, thanks for your answer. I know is missing. What I want to know if is possible for me to implemented using the SCALE engine. Can I use the libraries (Share.cpp, IO etc) to create shares and send them ? Is it secure ?

**Comment by NigelSmart** [comment]
Suggest you read the documentation and the associated papers

Nigel

**Comment by cnasikas** [comment]
Hi Nigel,

I read the documentation and the associated papers (not all of them). I read also this paper [Confidential Benchmarking based on MultipartyComputation](https://eprint.iacr.org/2015/1006.pdf) in which Damgard et al. describe the same problem (data from clients to players) and they proposed a protocol as a solution. In SPDZ-2 the protocol is provided by default ([ExternalIO](https://github.com/bristolcrypto/SPDZ-2/blob/89d463c9294c231b477b28a5ebd52c02a3c34eac/ExternalIO/README.md)).  Will SCALE-MAMBA provide the protocol described above in future releases ? 

I am willing to help with it. As far I understand the MAMBA compiler should support `read_from_socket, receive_from_client, write_to_socket` for `sint` type and `listen, acceptclientconnection` global functions. I am on the right direction or I am missing something ?

Thanks a lot for your help! I appreciate any comment / guidance.

**Comment by NigelSmart** [comment]
No plans to include this. Indeed this is one of the main reasons
we re-engineered the whole thing. Any connections you want to sockets
etc should be provided by your application which then talks to
the SCALE engine via the IO class. Otherwise we have to
predict various ways users want to configure a system and
maintain them.

Think of SCALE as a microprocessor, that does not understand
sockets. The sockets are provided by the OS, which is the
equivalent of your final application you build. Your application
is built outside MAMBA. MAMBA just provides the compiler
to produce the machine code to run on the micro-processor.
  - MAMBA is closer to an assembler more than a proper
    language.

Nigel

**Comment by cnasikas** [comment]
We implemented an external data importer following: [Confidential Benchmarking based on MultipartyComputation](https://eprint.iacr.org/2015/1006.pdf). 

Disclaimer: It is not ready for production yet.

https://github.com/Athena-MHMD/SCALE-MAMBA
